Repository openfun/fun-apps, pull requests merged in 2019-11, with the labels that each got.

#664 🐛(payment) fix broken migration 0002
  payment/migrations/0002_auto_20170615_1426.py
Labels: bug, needs review

#665 🔖(patch) bump release to 2.0.1+wb
  setup.cfg
Labels: FUN, needs review

#666 🔧(proctoring) add Proctor Exam configurable-lti-consumer LTI settings
  fun/envs/common_wb.py
  setup.cfg
Labels: FUN
