Repository openfun/fun-apps, pull requests merged in 2019-10, with the labels that each got.

#654 🔖(minor) bump version to 4.35.0
  setup.cfg
Labels: FUN, needs review

#655 📦(project) add missing statics & templates
  MANIFEST.in
  README.md
  scripts/manifest.sh
Labels: bug, critical, easy pick, needs review

#656 🔖(patch) bump version to 4.35.1
  setup.cfg
Labels: FUN, needs review

#657 🔧(lti) add Glowbl settings to our configurable LTI consumer
  fun/envs/common.py
Labels: improvement

#658 🔖(patch) bump version to 4.36
  setup.cfg
Labels: FUN

#661 🔖(major) bump version to 5.0.0
  setup.cfg
Labels: FUN, needs review
