Repository openfun/fun-apps, pull requests merged in 2020-01, with the labels that each got.

#667 🔥(selftest) Totaly remove selftest application
  MANIFEST.in
  fun/common_urls.py
  fun/envs/cms/common.py
  fun/envs/lms/common.py
  fun/templates/fun/emails/base_email.html
  selftest/__init__.py
  selftest/forms.py
  selftest/static/selftest/css/raw-theme.css
  selftest/static/selftest/css/table.css
  selftest/static/selftest/images/blue_banner.png
  selftest/static/selftest/images/logo-fun.png
  selftest/static/selftest/images/logo-funmooc.png
  selftest/tasks.py
  selftest/templates/selftest/base.html
  selftest/templates/selftest/index.html
  selftest/urls.py
  selftest/views.py
Labels: FUN, easy pick

#668 🔥(selftest) Totaly remove selftest application
  MANIFEST.in
  fun/common_urls.py
  fun/envs/cms/common.py
  fun/envs/lms/common.py
  fun/templates/fun/emails/base_email.html
  selftest/__init__.py
  selftest/forms.py
  selftest/static/selftest/css/raw-theme.css
  selftest/static/selftest/css/table.css
  selftest/static/selftest/images/blue_banner.png
  selftest/static/selftest/images/logo-fun.png
  selftest/tasks.py
  selftest/templates/selftest/index.html
  selftest/urls.py
Labels: FUN, easy pick

#669 🔥(videofront) set video upload panel read only
  fun/templates/cms/videoupload/index.html
  fun/templates/cms/videoupload/js/parameters-subtitle.underscore
  fun/templates/cms/videoupload/js/parameters.underscore
  fun/templates/cms/videoupload/js/video.underscore
Labels: FUN

#671 🔥(videofront) set video upload panel read only
  fun/templates/cms/videoupload/index.html
  fun/templates/cms/videoupload/js/parameters-subtitle.underscore
  fun/templates/cms/videoupload/js/parameters.underscore
  fun/templates/cms/videoupload/js/video.underscore
Labels: FUN

#673 🔖(minor) bump version to 5.2.0
  setup.cfg
Labels: FUN, easy pick

#672 🔖(minor) bump version to 2.2.0+wb
  setup.cfg
Labels: FUN, easy pick

#675 🔧(certificates) rewrite constants related to fun's PDF certificates urls
  backoffice/certificate_manager/utils.py
  backoffice/certificate_manager/views.py
  backoffice/templates/backoffice/certificate.html
  backoffice/templates/backoffice/user.html
  backoffice/tests/test_certificates.py
  fun/envs/lms/common.py
  fun/lms/urls.py
  fun_certificates/generator.py
Labels: FUN, bug

#676 🔖(fix) bump version to 5.2.1
  setup.cfg
Labels: FUN, bug

#677 🐛(static) use static.url template tag where it is required
  funsite/templates/funsite/parts/base.html
  payment/templates/payment/order.html
Labels: bug, needs review

#681 ⚡️(funsite) use cache for home page for authenticated users
  CHANGELOG.md
  funsite/templates/lms/index.html
Labels: easy pick, improvement

#682 🔖(minor) bump version to 5.3.0
  CHANGELOG.md
  setup.cfg
Labels: FUN, improvement
