Repository openfun/fun-apps, pull requests merged in 2020-04, with the labels that each got.

#687 ♻️(certificates) rewrite command changing `audit` enrollments to `honor`
  CHANGELOG.md
  fun/management/commands/course_mode_audit_to_honor.py
  fun/management/commands/tests/test_course_mode_audit_to_honor.py
  fun/templates/fun/emails/course_mode_audit_to_honor.html
Labels: FUN

#689 🔥(contact) remove fun-apps `contact` application
  contact/__init__.py
  contact/locale/fr/LC_MESSAGES/django.mo
  contact/locale/fr/LC_MESSAGES/django.po
  contact/templates/contact/contact.html
  contact/tests.py
  contact/urls.py
  contact/views.py
  fun/envs/lms/common.py
  fun/lms/urls.py
Labels: FUN

#690 🔖(minor) bump version to 5.4.0
  CHANGELOG.md
  setup.cfg
Labels: feature

#691 🔖(minor) bump version to 2.4.0+wb
  CHANGELOG.md
  setup.cfg
Labels: FUN

#692 🐛(certificates) fix email report recipient bug
  fun/management/commands/course_mode_audit_to_honor.py
Labels: bug
